poisson_ratio = 0.25;
mu = 1.0;
dip = 60;
lambda = 2 * mu * poisson_ratio / (1 - 2 * poisson_ratio);
alpha = (lambda + mu) / (lambda + 2 * mu);
ux = zeros(100, 100);

        [success, u, grad_u] = DC3Dwrapper(alpha,...
                                           [100, 100, 0.0],...
                                           0.0, dip,...
                                           [200, 00],...
                                           [150, 0],...
                                           [1.0, 1.0, 0.0]);
